# Generated by Django 3.2.9 on 2021-11-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
